-- Set Supabase Auth OTP expiry to 22 days (1900800 seconds)
-- This makes magic links valid for 22 days from generation
-- Note: In newer Supabase Auth versions, this is set via the Management API,
-- not directly via SQL (the auth.config table no longer exists).
-- Applied via:
--   PATCH /v1/projects/anigcqdquakinlzvyaur/config/auth
--   { "mailer_otp_exp": 1900800 }
--
-- This migration file is kept for documentation/reproducibility.
-- To verify the current value:
--   SELECT "mailer_otp_exp" FROM auth.config;  -- or check via Dashboard
